version: '3.7'
services:
  luac:
    build: ./
    volumes:
      - ./data:/data
#    restart: always
#    ports:
#      - 6379:6379
    networks:
      - my_network
    command:
      -


networks:
  my_network:
    name: my_network
    #    driver: bridge
    ipam:
      #      driver: default
      config:
        - subnet: 192.168.10.0/24